### ISSUE TITLE
stop_listening() seems to not work under Windows

### ISSUE THREAD

**Issue by irukard** [CaileanWilkinson/pybuzzers#1]
According to documentation `stop_listening()` should stop background task.
Yet this task seems to work after this command (windows 10, python 3.12.0).

```python
import pybuzzers

def main():
    buzzer = pybuzzers.get_all_buzzers()[0]
    buzzer.on_buzz(respond_to_press)
    buzzer.start_listening()
    buzzer.stop_listening()
    print("Stop!")
    while True:
        pass

def respond_to_press(buzzer_set: pybuzzers.BuzzerSet, buzzer: int):
    print(f"Buzz pressed on buzzer {buzzer}!")

if __name__ == "__main__":
    main()
```
And I can still receive and process events:
```
Stop!
Buzz pressed on buzzer 0!
Buzz pressed on buzzer 1!
Buzz pressed on buzzer 2!
Buzz pressed on buzzer 3!
```
Python is not my primary language (C and Rust is) so maybe I do something and silly :)

**Comment by CaileanWilkinson** [comment]
Thanks for letting me know! I have just pushed an update which I hope fixes this problem.

`stop_listening()` previously closed and reopened the usb connection, the theory being that this would force the thread listening to it to raise an exception and stop waiting for a response, so we could make it quit. I suspect (hope) the closing and reopening was happening too quickly to interrupt the listener process and so wasn't quitting properly.

The new version throws the whole connection away and starts a new one (which the listener thread won't have a reference to) and so now there should be no connection left for the listener thread to respond to.

I don't have a windows pc to test this on, so please let me know if it works.

**Comment by irukard** [comment]
Unfortunately adding `self.__interface = hid.device()` doesn't solve the problem.
I suppose the implementation of hidapi on windows is quite different than on linux/mac.

**Comment by CaileanWilkinson** [comment]
It is possible that hidapi does not raise the same exception when a read fails on windows as it does on Mac, or that when the connection is closed the read fails gracefully without raising an exception. I'll have to try it on a windows pc and have a look.

**Comment by DevJav** [comment]
just wanted to say that it's still not fixed at least for my Windows 11

**Comment by irukard** [comment]
My workaround was adding `__service_running` flag which was controlled in `start_listening` and `stop_listening` and checked in `__listen_loop`, not very elegant, but works good enough :)
Also I removed everything after `__interface.close()`
